version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nl-heat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19ix083pcuxfb"
s3_prefix = "nl-heat"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
